name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm init -y

    - run: npm install @openzeppelin/contracts-ethereum-package LykkeBusiness/openzeppelin-contracts-ethereum-package.git#a517ad7e3e12488a4595e4514da8fbd12c693f90 --save --only prod
    - run: npm install @openzeppelin/cli 2.8.1 --save --only prod
    
