name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm init -y

    - run: npm install @openzeppelin/contracts-ethereum-package --save LykkeCity/openzeppelin-quorum-contracts-ethereum-package.git#20e38b4dd9fe6a5424194e56a7b97eec5583e573
    - run: npm install @openzeppelin/cli --save 2.8.1
    
